node default {
  file { '/root/README':
    ensure => file,
    content => 'This is a readme',
    owner   => 'root',
  }
  group { 'resource puppygroup':
  name                 => puppygroup, # (namevar) The group name. While naming limitations vary by 
  ensure               => present, # Create or remove the group.  Default: `present`  
  #allowdupe            => # Whether to allow duplicate GIDs.  Default...
  #attribute_membership => # AIX only. Configures the behavior of the...
  #attributes           => # Specify group AIX attributes, as an array of...
  #auth_membership      => # Configures the behavior of the `members...
  #forcelocal           => # Forces the management of local accounts when...
  gid                  => 995 # The group ID.  Must be specified numerically....
  #ia_load_module       => # The name of the I&A module to use to manage this 
  #members              => # The members of the group. For platforms or...
  #provider             => # The specific backend to use for this `group...
  #system               => # Whether the group is a system group with lower...
  # ...plus any applicable metaparameters.
}
}
